name: datum_py39

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pycodestyle, pylint
      run: |
        bash tools/ci_build/ci_sanity.sh
    - name: Test with pytest
      run: |
        export PYTHONPATH=.
        bash tools/ci_testing/datum_cpu.sh
